# Generated by Django 5.0.3 on 2024-04-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smartmedical", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patient",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="patient",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Doctor",
        ),
        migrations.DeleteModel(
            name="Patient",
        ),
    ]
