# Generated by Django 5.0.3 on 2024-04-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartmedical", "0004_rename_user_id_prescription_patient_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prescription",
            name="patient_id",
            field=models.IntegerField(default=0),
        ),
    ]
