# Generated by Django 5.0.3 on 2024-04-28 01:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartmedical", "0005_alter_prescription_patient_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("appointment_title", models.CharField(max_length=200)),
                ("appointment_description", models.TextField()),
                ("appointment_date", models.DateField()),
                ("appointment_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("patient_id", models.IntegerField(default=0)),
                ("assosiated_doctor", models.CharField(max_length=100)),
                ("doctor_email", models.EmailField(max_length=100)),
                ("caretaker", models.CharField(max_length=100)),
                ("caretaker_email", models.EmailField(max_length=100)),
                (
                    "caretaker_phone",
                    models.BigIntegerField(
                        validators=[
                            django.core.validators.MinLengthValidator(10),
                            django.core.validators.MaxLengthValidator(12),
                        ]
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="appointment_date",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="appointment_description",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="appointment_time",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="appointment_title",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="exercise_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="exercise_time",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="exercise_type",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="experience",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient_id",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="patient_name",
        ),
        migrations.RemoveField(
            model_name="prescription",
            name="registered_username",
        ),
        migrations.AddField(
            model_name="prescription",
            name="instructions",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exercise_name", models.CharField(max_length=200)),
                (
                    "exercise_type",
                    models.CharField(
                        choices=[
                            ("aerobic", "Aerobic"),
                            ("strength", "Strength"),
                            ("flexibility", "Flexibility"),
                        ],
                        max_length=20,
                    ),
                ),
                ("exercise_time", models.TimeField()),
                ("discription", models.TextField()),
                (
                    "prescription",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartmedical.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicineConsumed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time_taken", models.TimeField()),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="smartmedical.patient",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="prescription",
            name="patient",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="smartmedical.patient",
            ),
        ),
    ]
