# Generated by Django 5.0.3 on 2024-04-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smartmedical", "0006_appointment_patient_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="caretaker_phone",
            field=models.CharField(max_length=12),
        ),
    ]
