# Generated by Django 5.0.3 on 2024-04-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("smartmedical", "0008_remove_medicineconsumed_patient_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicineconsumed",
            name="caretaker_email",
            field=models.EmailField(default="rakshitahalaj@gmail.com", max_length=100),
        ),
        migrations.AlterField(
            model_name="patient",
            name="caretaker_email",
            field=models.EmailField(default="rakshitahalaj@gmail.com", max_length=100),
        ),
    ]
