# Generated by Django 5.0.3 on 2024-04-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0015_chatmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ChatMessage",
        ),
    ]
